import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body>
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
        >
            <SidebarProvider>
                <div className="flex">
                    <AppSidebar />
                    <main className="flex-1">
                        <div className="flex justify-between items-center p-4">
                            <SidebarTrigger />
                        </div>
                        {children}
                    </main>
                </div>
            </SidebarProvider>
        </ThemeProvider>
        </body>
        </html>
    );
}
